"""add sports management

Revision ID: 3e22b5f59faa
Revises: 78feb1bb58cd
Create Date: 2026-08-28 11:10:04.162318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e22b5f59faa'
down_revision = '78feb1bb58cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_sports_name_not_blank'),
    sa.CheckConstraint('max_players BETWEEN 1 AND 20', name='ck_sports_max_players_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_sports_name'),
    sa.UniqueConstraint('normalized_name', name='uq_sports_normalized_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports')
    # ### end Alembic commands ###
